services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/pizzaria.db:/app/pizzaria.db
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./Novo_Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
